/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import org.example.riddle.Riddle01
import org.example.solution.Solver01

class AppTest {
  @Test
  fun appHasAGreeting() {
    val classUnderTest = Solver01(Riddle01())
    //    assertNotNull(classUnderTest.greeting, "app should have a greeting")
  }
}
