/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.riddle.Riddle01
import org.example.solution.Solver01

suspend fun main() {
  println(Solver01(Riddle01()).solve())
}
